import express from 'express';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { createWorkoutPlan } from '../../service/impl/workoutPlan/setWorkoutPlan/setWorkoutPlan.impl';
import { validate } from '../../middleware/globalValidator/globalValidator.md';
import { validateUpdatedWorkoutPlan, validateWorkoutPlan } from '../../utils/validators.md';
import { showWorkoutPlans } from '../../service/impl/workoutPlan/showWorkoutPlans/showWorkoutPlans.impl';
import { showWorkoutPlan } from '../../service/impl/workoutPlan/showWorkoutPlan/showWorkoutPlan.impl';
import { editAndUpdateWorkoutPlan } from '../../service/impl/workoutPlan/editAndUpdateWorkoutPlan/editAndUpdateWorkoutPlan.impl';
const router = express.Router();
router.post('/create-work-out-plan', authenticationToken, validate(validateWorkoutPlan), createWorkoutPlan);
router.get('/show-workout-plans', authenticationToken, showWorkoutPlans);
router.get('/show-workout-plan/:id', authenticationToken, showWorkoutPlan);
router.put('/update-workout-plan/:id', authenticationToken, validate(validateUpdatedWorkoutPlan), editAndUpdateWorkoutPlan);
export default router;