import express from 'express';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { sendReminder } from '../../service/impl/reminder/sendReminder/sendReminder.impl';
import { validate } from '../../middleware/globalValidator/globalValidator.md';
import { validateSendReminderMessage, validateUpdatedReminderMessage } from '../../utils/validators.md';
import { showReminders } from '../../service/impl/reminder/showReminders/showReminders.impl';
import { showReminder } from '../../service/impl/reminder/showReminder/showReminder.impl';
import { editAndUpdateReminder } from '../../service/impl/reminder/editAndUpdateReminder/editAndUpdateReminder.impl';
const router = express.Router();
router.post('/send-reminder', authenticationToken, validate(validateSendReminderMessage), sendReminder);
router.get('/show-reminders', authenticationToken, showReminders);
router.get('/show-reminder/:id', authenticationToken, showReminder);
router.put('/update-reminder/:id', authenticationToken, validate(validateUpdatedReminderMessage), editAndUpdateReminder);
export default router;