import express from 'express';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { createProfile } from '../../service/impl/profile/createProfile/createProfile.impl';
import { validate } from '../../middleware/globalValidator/globalValidator.md';
import { validateProfileRegistration } from '../../utils/validators.md';
import { fetchProfiles } from '../../service/impl/profile/fetchprofiles/fetchProfiles.impl';
import { fetchProfile } from '../../service/impl/profile/fetchProfile/fetchProfile.impl';
import { updateProfile } from '../../service/impl/profile/updateProfile/updateProfile.impl';
import { deleteProfile } from '../../service/impl/profile/deleteProfile/deleteProfile.impl';
const router = express.Router();
router.post('/create-profile', authenticationToken, validate(validateProfileRegistration), createProfile);
router.get('/fetch-profiles', authenticationToken, fetchProfiles);
router.get('/fetch-profile/:id', authenticationToken, fetchProfile);
router.put('/update-profile/:id', authenticationToken, validate(validateProfileRegistration), updateProfile);
router.delete('/delete-profile/:id', authenticationToken, deleteProfile);
export default router;