import express from 'express';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { setGoal } from '../../service/impl/goal/setGoal/setGoal.impl';
import { validate } from '../../middleware/globalValidator/globalValidator.md';
import { validateGoalCreation, validateUpdatedGoal } from '../../utils/validators.md';
import { showGoals } from '../../service/impl/goal/showGoals/showGoals.impl';
import { showGoal } from '../../service/impl/goal/showGoal/showGoal.impl';
import { editAndUpdateGoal } from '../../service/impl/goal/updateGoal/updateGoal.impl';
const router = express.Router();
router.post('/set-goal', authenticationToken, validate(validateGoalCreation), setGoal);
router.get('/show-goals', authenticationToken, showGoals);
router.get('/show-goal/:id', authenticationToken, showGoal);
router.put('/update-goal/:id', authenticationToken, validate(validateUpdatedGoal), editAndUpdateGoal);
export default router;