import express from 'express';
import { register } from '../../service/impl/auth/register/register.impl';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { validate } from '../../middleware/globalValidator/globalValidator.md';
import { validateUserLogin, validateUserRegistration } from '../../utils/validators.md';
import { login } from '../../service/impl/auth/login/login.impl';
import { fetchUsers } from '../../service/impl/auth/fetchUsers/fetchUser.impl';
const router = express.Router();
router.post('/register', authenticationToken, validate(validateUserRegistration), register);
router.post('/login', authenticationToken, validate(validateUserLogin), login);
router.get('/fetch-users', fetchUsers);
export default router;