import express from 'express';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { validate } from '../../middleware/globalValidator/globalValidator.md';
import { validateSleepDuration } from '../../utils/validators.md';
import { showSleepingCalendars } from '../../service/impl/sleep/showSleepingCalendars/showSleepingCalendars.impl';
import { showSleepingCalendar } from '../../service/impl/sleep/showSleepingCalendar/showSleepingCalendar.impl';
import { setSleepingCalendar } from '../../service/impl/sleep/setSleepingCalendar/setSleepingCalendar.impl';
const router = express.Router();
router.post('/set-sleeping-calendar', authenticationToken, validate(validateSleepDuration), setSleepingCalendar);
router.get('/fetch-sleeping-calendars', authenticationToken, showSleepingCalendars);
router.get('/fetch-sleeping-calendar/:id', authenticationToken, showSleepingCalendar);
export default router;