import  express from 'express';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { createChallenge } from '../../service/impl/challenge/createChallenge/createChallenge.impl';
import { validate } from '../../middleware/globalValidator/globalValidator.md';
import { validateCreatedChallenge, validateUpdatedChallenge } from '../../utils/validators.md';
import { showChallenges } from '../../service/impl/challenge/showChallenges/showChallenges.impl';
import { showChallenge } from '../../service/impl/challenge/showChallenge/showChallenge.impl';
import { editAndUpdateChallenge } from '../../service/impl/challenge/editAndUpdateChallenge/editAndUpdateChallenge.impl';
const router = express.Router();
router.post('/create-challenge', authenticationToken, validate(validateCreatedChallenge), createChallenge);
router.get('/show-challenges', authenticationToken, showChallenges);
router.get('/show-challenge/:id', authenticationToken, showChallenge);
router.put('/update-challenge/:id', authenticationToken, validate(validateUpdatedChallenge), editAndUpdateChallenge);
export default router;