import express from 'express';
import { authenticationToken } from '../../middleware/auth/auth.middleware';
import { sendPushNoficationMessage } from '../../service/impl/notification/sendNotification/sendNotification.impl';
import { showPushNoficationMessages } from '../../service/impl/notification/showNotifications/showNotifications.impl';
import { showPushNoficationMessage } from '../../service/impl/notification/showNotification/showNotification.impl';
import { editAndUpdatePushNoficationMessage } from '../../service/impl/notification/updateNotification/updateNotification.impl';
const router = express.Router();
router.post('/send-notification', authenticationToken, sendPushNoficationMessage);
router.get('/show-notifications', authenticationToken, showPushNoficationMessages);
router.get('/show-notification/:id', authenticationToken, showPushNoficationMessage);
router.put('/update-notification/:id', authenticationToken, editAndUpdatePushNoficationMessage);
export default router;